export const ACTION_TYPE = 'ACTION_TYPE';
export const AUTHENTICATION_TYPE = 'AUTHENTICATION_TYPE';
export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_TRANSACTION_LOG = 'ADD_TRANSACTION_LOG';

